### ISSUE TITLE
无法解析的外部符号

### ISSUE THREAD

**Issue by huolu1987** [changfeng1050/SerialWizard#2]
你好，
我下载了你的工程打开编译，提示无法解析的外部符号，如下图：
![图片](https://user-images.githubusercontent.com/19585799/54335656-a62aaf80-4664-11e9-8674-88caa9643db8.png)
请问还有什么需要引入的吗？

**Comment by changfeng1050** [comment]
你用的是什么IDE

**Comment by huolu1987** [comment]
Qt 跟 visual studio 都试了一下，报相同的错误提示

**Comment by changfeng1050** [comment]
需要用qt自带的mingw编译器

**Comment by huolu1987** [comment]
这两天折腾了一下Qt开发环境，终于把这个工程跑起来了，总结一下原因主要有两个：
第一：有些文件并没有被添加到工程，需要手动add一下data及serial目录下的文件；
第二：工程对于串口，网口的依赖需要手动添加到工程属性的设置中，具体可以参考：
https://www.cnblogs.com/Braveliu/p/9361792.html
https://blog.csdn.net/ningzb/article/details/39557431
做一下记录，感谢原作者的分享啊~

**Comment by lilealyh** [comment]
是不是有些方法没实现呢

debug/mainwindow.o: In function `MainWindow::openReadWriter()':
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:464: undefined reference to `TcpClientReadWriter::TcpClientReadWriter(QObject*)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:465: undefined reference to `TcpClientReadWriter::setAddress(QString const&)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:466: undefined reference to `TcpClientReadWriter::setPort(int)'
debug/mainwindow.o: In function `MainWindow::updateSendData(bool, QString const&)':
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:835: undefined reference to `SerialController::setIsHex(bool)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:836: undefined reference to `SerialController::setData(QString)'
debug/mainwindow.o: In function `MainWindow::readSettings()':
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:917: undefined reference to `NormalSerialController::NormalSerialController()'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:918: undefined reference to `SerialController::setIsHex(bool)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:919: undefined reference to `SerialController::setAutoSend(bool)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:920: undefined reference to `SerialController::setLoopSend(bool)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:921: undefined reference to `SerialController::setAutoSendInterval(int)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:922: undefined reference to `SerialController::setData(QString)'
debug/mainwindow.o: In function `MainWindow::updateSendType()':
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1203: undefined reference to `NormalSerialController::NormalSerialController(SerialController*)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1205: undefined reference to `LineSerialController::LineSerialController(SerialController*)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1207: undefined reference to `FrameSerialController::FrameSerialController(SerialController*)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1209: undefined reference to `FrameSerialController::setFrameInfo(FrameInfo const&)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1213: undefined reference to `FixedBytesSerialController::FixedBytesSerialController(SerialController*)'
F:\git project\0325\build-SerialWizard-Desktop_Qt_5_12_2_MinGW_64_bit-Debug/../SerialWizard/mainwindow.cpp:1214: undefined reference to `FixedBytesSerialController::setFixedCount(int)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [Makefile.Debug:109: debug/SerialWizard.exe] Error 1
mingw32-make: *** [Makefile:38: debug] Error 2
