### ISSUE TITLE
必须有一个返回值

### ISSUE THREAD

**Issue by huolu1987** [changfeng1050/SerialWizard#3]
![图片](https://user-images.githubusercontent.com/19585799/54335801-0f122780-4665-11e9-8f33-67496a244e28.png)

qint64 MainWindow::writeData(const QByteArray &data) {
    if (!data.isEmpty() && isReadWriterConnected()) {
        auto count = _readWriter->write(data);
        displaySentData(data);
        sendCount += count;
        emit writeBytesChanged(sendCount);
    }
}
这里提示该方法必须有一个返回值，请解释一下呗，谢谢

**Comment by changfeng1050** [comment]
这里应该 
`qint64 MainWindow::writeData(const QByteArray &data) {
if (!data.isEmpty() && isReadWriterConnected()) {
auto count = _readWriter->write(data);
displaySentData(data);
sendCount += count;
emit writeBytesChanged(sendCount);
return sendCount;
}
return 0;
}`

**Comment by changfeng1050** [comment]
``` C++
qint64 MainWindow::writeData(const QByteArray &data) 
{ 
if (!data.isEmpty() && isReadWriterConnected()) {
 auto count = _readWriter->write(data); 
displaySentData(data);
 sendCount += count; 
emit writeBytesChanged(sendCount); 
return sendCount; } return 0; }

```

**Comment by huolu1987** [comment]
ok, thank you!
